USE [DDCP];
GO
SELECT COUNT(*) AS entidades FROM dbo.CAT_ENTIDAD;
SELECT YEAR(PERIODO) AS anio, MONTH(PERIODO) AS mes, COUNT(*) AS registros, SUM(NUM_DIS_DECOMISADOS) AS dispositivos, SUM(CONVERT(bigint, PERSONAS_P_DISPOSICION)) AS personas FROM dbo.DISPOSITIVOS_DECOMISADOS GROUP BY YEAR(PERIODO), MONTH(PERIODO) ORDER BY anio, mes;
SELECT ID_ENTIDAD, PERIODO, COUNT(*) AS duplicados FROM dbo.DISPOSITIVOS_DECOMISADOS GROUP BY ID_ENTIDAD, PERIODO HAVING COUNT(*) > 1;
SELECT name, current_value FROM sys.sequences WHERE name = 'SEQ_DECOMISO';
SELECT ID_USUARIO, USUARIO, ROL, ES_NACIONAL, ID_ENTIDAD, HABILITADO FROM dbo.ING_USUARIO;
SELECT ID_CARGA, ID_USUARIO, PERIODO, ESTADO, FECHA_CREACION, FECHA_CONFIRMACION FROM dbo.DDCP_CARGA ORDER BY FECHA_CREACION DESC;
SELECT COUNT(*) AS versiones_historicas FROM dbo.DDCP_HISTORICO;
