USE DDCP;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

UPDATE dbo.CAT_ENTIDAD
SET NOMBRE_ENTIDAD = CASE ID_ENTIDAD
    WHEN 7 THEN N'Ciudad de México'
    WHEN 11 THEN N'Estado de México'
    WHEN 16 THEN N'Michoacán'
    WHEN 19 THEN N'Nuevo León'
    WHEN 22 THEN N'Querétaro'
    WHEN 24 THEN N'San Luis Potosí'
    WHEN 31 THEN N'Yucatán'
END
WHERE ID_ENTIDAD IN (7, 11, 16, 19, 22, 24, 31)
    AND CHARINDEX(N'?', NOMBRE_ENTIDAD) > 0;

COMMIT TRANSACTION;

SELECT ID_ENTIDAD, NOMBRE_ENTIDAD
FROM dbo.CAT_ENTIDAD
WHERE ID_ENTIDAD IN (7, 11, 16, 19, 22, 24, 31)
ORDER BY ID_ENTIDAD;
