USE [DDCP];
GO
SET XACT_ABORT ON;
BEGIN TRY
    BEGIN TRANSACTION;
    IF OBJECT_ID('dbo.CAT_ENTIDAD') IS NULL OR OBJECT_ID('dbo.DISPOSITIVOS_DECOMISADOS') IS NULL THROW 50001, 'Faltan las tablas originales de DDCP.', 1;
    IF EXISTS (SELECT ID_ENTIDAD FROM dbo.CAT_ENTIDAD GROUP BY ID_ENTIDAD HAVING COUNT(*) > 1) THROW 50001, 'Existen IDs de entidad duplicados.', 1;
    IF EXISTS (SELECT NOMBRE_ENTIDAD FROM dbo.CAT_ENTIDAD GROUP BY NOMBRE_ENTIDAD HAVING COUNT(*) > 1) THROW 50001, 'Existen nombres de entidad duplicados.', 1;
    IF EXISTS (SELECT ID_DISPOSITIVO_DECOMISADO FROM dbo.DISPOSITIVOS_DECOMISADOS GROUP BY ID_DISPOSITIVO_DECOMISADO HAVING COUNT(*) > 1) THROW 50001, 'Existen IDs de decomiso duplicados.', 1;
    IF EXISTS (SELECT 1 FROM dbo.DISPOSITIVOS_DECOMISADOS d LEFT JOIN dbo.CAT_ENTIDAD e ON e.NOMBRE_ENTIDAD = d.NOMBRE_ENTIDAD WHERE e.ID_ENTIDAD IS NULL) THROW 50001, 'Hay decomisos cuya entidad no existe en el catálogo.', 1;
    IF EXISTS (SELECT 1 FROM dbo.DISPOSITIVOS_DECOMISADOS WHERE NUM_DIS_DECOMISADOS < 0 OR PERSONAS_P_DISPOSICION < 0) THROW 50001, 'Hay cantidades negativas.', 1;
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.CAT_ENTIDAD') AND name = 'UX_CAT_ENTIDAD_ID') CREATE UNIQUE INDEX UX_CAT_ENTIDAD_ID ON dbo.CAT_ENTIDAD(ID_ENTIDAD);
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.DISPOSITIVOS_DECOMISADOS') AND name = 'UX_DECOMISO_ID') CREATE UNIQUE INDEX UX_DECOMISO_ID ON dbo.DISPOSITIVOS_DECOMISADOS(ID_DISPOSITIVO_DECOMISADO);
    IF COL_LENGTH('dbo.DISPOSITIVOS_DECOMISADOS', 'ID_ENTIDAD') IS NULL EXEC('ALTER TABLE dbo.DISPOSITIVOS_DECOMISADOS ADD ID_ENTIDAD int NULL;');
    IF COL_LENGTH('dbo.DISPOSITIVOS_DECOMISADOS', 'PERIODO') IS NULL EXEC('ALTER TABLE dbo.DISPOSITIVOS_DECOMISADOS ADD PERIODO date NULL;');
    IF COL_LENGTH('dbo.DISPOSITIVOS_DECOMISADOS', 'FECHA_INGESTA') IS NULL EXEC('ALTER TABLE dbo.DISPOSITIVOS_DECOMISADOS ADD FECHA_INGESTA datetime2 NULL;');
    IF COL_LENGTH('dbo.DISPOSITIVOS_DECOMISADOS', 'REVISION') IS NULL EXEC('ALTER TABLE dbo.DISPOSITIVOS_DECOMISADOS ADD REVISION int NOT NULL CONSTRAINT DF_DECOMISO_REVISION DEFAULT 1;');
    -- Las fechas originales se conservan. El periodo histórico se deriva de FECHA_CREACION.
    EXEC('UPDATE d SET ID_ENTIDAD = e.ID_ENTIDAD FROM dbo.DISPOSITIVOS_DECOMISADOS d JOIN dbo.CAT_ENTIDAD e ON e.NOMBRE_ENTIDAD = d.NOMBRE_ENTIDAD WHERE d.ID_ENTIDAD IS NULL;
          UPDATE dbo.DISPOSITIVOS_DECOMISADOS SET PERIODO = DATEFROMPARTS(YEAR(FECHA_CREACION), MONTH(FECHA_CREACION), 1) WHERE PERIODO IS NULL;
          IF EXISTS (SELECT ID_ENTIDAD, PERIODO FROM dbo.DISPOSITIVOS_DECOMISADOS GROUP BY ID_ENTIDAD, PERIODO HAVING COUNT(*) > 1) THROW 50001, ''Hay periodos duplicados por entidad. No se modificó la base.'', 1;
          ALTER TABLE dbo.DISPOSITIVOS_DECOMISADOS ALTER COLUMN ID_ENTIDAD int NOT NULL;
          ALTER TABLE dbo.DISPOSITIVOS_DECOMISADOS ALTER COLUMN PERIODO date NOT NULL;');
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.DISPOSITIVOS_DECOMISADOS') AND name = 'UX_DECOMISO_PERIODO') EXEC('CREATE UNIQUE INDEX UX_DECOMISO_PERIODO ON dbo.DISPOSITIVOS_DECOMISADOS(ID_ENTIDAD, PERIODO);');
    IF OBJECT_ID('dbo.FK_DECOMISO_ENTIDAD') IS NULL EXEC('ALTER TABLE dbo.DISPOSITIVOS_DECOMISADOS WITH CHECK ADD CONSTRAINT FK_DECOMISO_ENTIDAD FOREIGN KEY (ID_ENTIDAD) REFERENCES dbo.CAT_ENTIDAD(ID_ENTIDAD);');
    IF OBJECT_ID('dbo.CK_DECOMISO_CANTIDADES') IS NULL EXEC('ALTER TABLE dbo.DISPOSITIVOS_DECOMISADOS WITH CHECK ADD CONSTRAINT CK_DECOMISO_CANTIDADES CHECK (NUM_DIS_DECOMISADOS >= 0 AND PERSONAS_P_DISPOSICION >= 0);');
    IF OBJECT_ID('dbo.CK_DECOMISO_PERIODO') IS NULL EXEC('ALTER TABLE dbo.DISPOSITIVOS_DECOMISADOS WITH CHECK ADD CONSTRAINT CK_DECOMISO_PERIODO CHECK (DAY(PERIODO) = 1);');
    IF OBJECT_ID('dbo.SEQ_DECOMISO', 'SO') IS NULL
    BEGIN
        DECLARE @inicio bigint = (SELECT COALESCE(MAX(CONVERT(bigint, ID_DISPOSITIVO_DECOMISADO)), 0) + 1 FROM dbo.DISPOSITIVOS_DECOMISADOS);
        IF @inicio > 2147483647 THROW 50001, 'Se agotó el rango de IDs de decomiso.', 1;
        DECLARE @sql nvarchar(max) = N'CREATE SEQUENCE dbo.SEQ_DECOMISO AS int START WITH ' + CONVERT(nvarchar(20), @inicio) + N' INCREMENT BY 1;';
        EXEC(@sql);
    END;
    COMMIT;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK;
    THROW;
END CATCH;
GO
