USE [DDCP];
GO
SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF OBJECT_ID('dbo.ING_USUARIO') IS NULL
CREATE TABLE dbo.ING_USUARIO (
    ID_USUARIO int IDENTITY PRIMARY KEY, USUARIO nvarchar(80) NOT NULL UNIQUE, NOMBRE nvarchar(160) NOT NULL, PASSWORD_HASH varchar(100) NOT NULL,
    ROL varchar(30) NOT NULL, ES_NACIONAL bit NOT NULL, ID_ENTIDAD int NULL, HABILITADO bit NOT NULL DEFAULT 1, FECHA_CREACION datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ING_USUARIO_ENTIDAD FOREIGN KEY (ID_ENTIDAD) REFERENCES dbo.CAT_ENTIDAD(ID_ENTIDAD),
    CONSTRAINT CK_ING_USUARIO_ROL CHECK (ROL IN ('SUPER_USUARIO', 'ENLACE_ESTATAL', 'CONSULTA')),
    CONSTRAINT CK_ING_USUARIO_ALCANCE CHECK ((ES_NACIONAL = 1 AND ID_ENTIDAD IS NULL) OR (ES_NACIONAL = 0 AND ID_ENTIDAD IS NOT NULL)),
    CONSTRAINT CK_ING_SUPER_NACIONAL CHECK (ROL <> 'SUPER_USUARIO' OR ES_NACIONAL = 1)
);
IF OBJECT_ID('dbo.ING_MODULO') IS NULL CREATE TABLE dbo.ING_MODULO (CLAVE varchar(40) PRIMARY KEY, NOMBRE nvarchar(160) NOT NULL, HABILITADO bit NOT NULL DEFAULT 1);
IF NOT EXISTS (SELECT 1 FROM dbo.ING_MODULO WHERE CLAVE = 'DDCP') INSERT dbo.ING_MODULO(CLAVE, NOMBRE) VALUES ('DDCP', N'Dispositivos decomisados en centros penitenciarios');
IF OBJECT_ID('dbo.ING_USUARIO_MODULO') IS NULL CREATE TABLE dbo.ING_USUARIO_MODULO (ID_USUARIO int NOT NULL REFERENCES dbo.ING_USUARIO(ID_USUARIO), CLAVE varchar(40) NOT NULL REFERENCES dbo.ING_MODULO(CLAVE), PRIMARY KEY(ID_USUARIO, CLAVE));
IF OBJECT_ID('dbo.DDCP_CARGA') IS NULL
CREATE TABLE dbo.DDCP_CARGA (
    ID_CARGA uniqueidentifier PRIMARY KEY, ID_USUARIO int NOT NULL, PERIODO date NOT NULL, ESTADO varchar(15) NOT NULL,
    NOMBRE_ARCHIVO nvarchar(255) NOT NULL, ARCHIVO varbinary(max) NOT NULL, FILAS_JSON nvarchar(max) NOT NULL, FECHA_CREACION datetime2 NOT NULL DEFAULT SYSUTCDATETIME(), FECHA_CONFIRMACION datetime2 NULL,
    CONSTRAINT CK_DDCP_CARGA_ESTADO CHECK (ESTADO IN ('PREVIA', 'CONFIRMADA', 'CANCELADA')), CONSTRAINT CK_DDCP_CARGA_JSON CHECK (ISJSON(FILAS_JSON) = 1)
);
IF OBJECT_ID('dbo.DDCP_HISTORICO') IS NULL
CREATE TABLE dbo.DDCP_HISTORICO (
    ID_HISTORICO bigint IDENTITY PRIMARY KEY, ID_DISPOSITIVO_DECOMISADO int NOT NULL, ID_ENTIDAD int NOT NULL, NOMBRE_ENTIDAD varchar(100) NOT NULL,
    PERIODO date NOT NULL, NUM_DIS_DECOMISADOS numeric(18,0) NOT NULL, PERSONAS_P_DISPOSICION int NOT NULL, REVISION int NOT NULL, HABILITADO bit NOT NULL,
    FECHA_CREACION datetime NOT NULL, FECHA_MODIFICACION datetime NULL, FECHA_INGESTA datetime2 NULL, ID_CARGA uniqueidentifier NOT NULL REFERENCES dbo.DDCP_CARGA(ID_CARGA), ID_USUARIO int NOT NULL, FECHA_HISTORICO datetime2 NOT NULL DEFAULT SYSUTCDATETIME()
);
COMMIT;
GO
